name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase actor
        id: set_actor
        run: echo "::set-output name=github_actor::${{ github.actor,, }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ steps.set_actor.outputs.github_actor }}/cloudflare-ddns:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ steps.set_actor.outputs.github_actor }}/cloudflare-ddns:latest